---
title: 'Homework 2 Question 3'
author: 'Yuval Saraf'
date: '05/29/2020'
output: html_document
---
Following an extensive study a researcher wants to test the difference between two groups

```{r}
Groap_A = c(1.25310535, 0.55464140, 0.30128300, 1.29312466, 0.99455579,
            0.51417430, 2.00783240, 0.42224244, 2.17877257, 3.21778902,
            0.55782935, 0.59461765, 0.97739581, 0.20986658, 0.30944786,
            1.10593627, 0.77418776, 0.08967408,1.10817666, 0.24726425,
            1.57198685, 4.83281274, 0.43113213, 2.73038931, 1.13683142,
            0.81336825, 0.83700649, 1.78476540, 2.31247163, 2.90988727)
Groap_B = c(2.94928948, 0.70302878, 0.69016263, 1.25069011, 0.43649776,
           0.22462232, 0.39231981, 1.57634350, 0.42792839, 0.19608026,
           0.37724368, 0.07071508, 0.03962611, 0.38580831, 2.63928857,
           0.78220807, 0.66454197, 0.95685690,0.02484568, 0.21600677,
           0.88031195, 0.13567357, 0.68181725, 0.20116062,0.48347620,
           0.50102846, 0.15668497, 0.71992076, 0.68549794, 0.86150777)
```

The researcher approached you to help figure out if the difference between the groups is statistically valid.


1. Can you perform a T-test? If you can, perform a T-test and explain the results. If the answer is no, explain why not. Remember the T-test assumption (random sampling, normality of data distribution, ….) (R code)

2. Can you use a non parametric test to compare the mean of the two groups? If yes, explain the test and show the calculation (R code)

3. To compare the mean of the two groups, we can take the permutation test approach. 
    1. Perform randomly 20 permutations and observe the difference in mean [i.e, Randomly shuffle the labels of the two original groups, such that two new 'permutated' groups will be obtained, each with 30 numbers. Then calculate the mean of each group and the difference between the means under all 20 permutations]. (R code)
    2. Create a function that will generate the realizations as described in 3.1 and will output the difference between the means of the two 'permutated' groups. (R code)
    3. Run 1 million permutations and calculate the p-value directly from the permutations - that is, (1+H)/N whereas H is the number of times the permutations have higher score (the score is the difference between the means of the two groups) compared to the score of the real (un-permuted) data.  (R code)
    4. Run only 1e3 permutations and then plot the histogram of the scores obtained - it should be close to normal distribution - then calculate the z-score of the real data using that normal distribution. Finally, calculate the p-value from the z-score. (R code)
    5. Compare the results 3.3 to 3.4 and explain.